export const navDetails = [
  {
    name: "Home",
    path: "/",
  },
  {
    name: "Products",
    path: "/products",
  },
  {
    name: "About",
    path: "/about",
  },
];

export const productImages = [
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
];
