export const navDetails = [
  {
    name: "Home",
    path: "/",
  },
  {
    name: "Products",
    path: "/products",
  },
  {
    name: "About",
    path: "/about",
  },
];

export const productImages = [
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
  "https://i.imgur.com/6qObK1y.jpeg",
  "https://i.imgur.com/H4VCLan.jpeg",
  "https://i.imgur.com/gygwW5y.jpeg",
];
export const reviews = [
  {
    id: "rev_001",
    names: "Jide Alabi",
    rating: 5,
    title: "Comfort on another level",
    comment:
      "I wore these all day and my feet didn’t hurt at all. Super lightweight and stylish. Definitely buying another pair.",
    product: "AirFlex Runner",
    size: "42",
    location: "Lagos, Nigeria",
    avatar: "/images/reviews/jide.jpg",
    date: "2026-01-18",
    verified: true,
  },
  {
    id: "rev_002",
    names: "Amara Okeke",
    rating: 5,
    title: "Exactly like the pictures",
    comment:
      "The quality is premium. The stitching, the sole, everything feels durable. Delivery was fast too.",
    product: "Urban Street Low",
    size: "39",
    location: "Abuja, Nigeria",
    avatar: "/images/reviews/amara.jpg",
    date: "2026-01-10",
    verified: true,
  },
  {
    id: "rev_003",
    names: "Tunde Bello",
    rating: 4,
    title: "Clean design 🔥",
    comment:
      "Very clean and minimal. Fits perfectly. I get compliments every time I step out.",
    product: "Classic Mono White",
    size: "43",
    location: "Ibadan, Nigeria",
    avatar: "/images/reviews/tunde.jpg",
    date: "2025-12-29",
    verified: true,
  },
  {
    id: "rev_004",
    names: "Zainab Musa",
    rating: 5,
    title: "Worth every naira",
    comment:
      "The cushioning is soft but supportive. You can tell it’s made with quality materials.",
    product: "CloudStep Pro",
    size: "38",
    location: "Port Harcourt, Nigeria",
    avatar: "/images/reviews/zainab.jpg",
    date: "2025-12-18",
    verified: true,
  },
  {
    id: "rev_005",
    names: "David Eze",
    rating: 5,
    title: "My new favorite sneakers",
    comment:
      "Feels premium from the box to the sole. Packaging was neat and delivery was smooth.",
    product: "Velocity X",
    size: "44",
    location: "Enugu, Nigeria",
    avatar: "/images/reviews/david.jpg",
    date: "2025-12-02",
    verified: false,
  },
];
